event_inherited(); 
component = true;
depth = -4;
gridX = noone; 
gridY = noone;
componentCode = noone; 
move = 0; 
infoText = "no infoText";
class = "default";
portraitSpr = spr_port_knight;
xOffset = 0;
faces = false;
facingDir = 2;
incapacitated = false;
